#hull configuration

---
thrusters:
     thruster1:
         type: azimuth
         position: [1,-0.5,-0.95]
         Kt: 0.5
         Dp: 0.2
     thruster2:
         type: azimuth
         position: [-1,-0.5,-0.95]
         Kt: 0.5
         Dp: 0.2
